#!/usr/bin/env bash
# configure web-02 to be identical to web-01
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html

otherdefault="/etc/nginx/sites-enabled/default"
location="\\\tadd_header X-Served-By \$hostname;"
sudo sed -i "30i $location" "$otherdefault"
sudo service nginx restart
